<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Stock Monitor</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/stylesheets/dashboard.css" rel="stylesheet">
  </head>

  <body>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <a class="navbar-brand col-sm-12 col-md-12 mr-0" href="#">雪球投资组合监控小帮手</a>
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="/">
                  <span data-feather="home"></span>
                  控制台 <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/portfolios">
                  <span data-feather="file"></span>
                  组合列表
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  监控提醒
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  运行日志
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                  系统设置
                </a>
              </li>
            </ul>


          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">控制台</h1>
          </div>

          <h2>监控组合</h2>
          <div class="table-responsive">
            <table class="table table-striped table-bordered rounded">
              <thead>
                <tr>
                  <th>#标识</th>
                  <th>名称</th>
                  <th>状态</th>
                  <th>最近调仓</th>
                  <th>日涨跌</th>
                  <th>月涨跌</th>
                  <th>净值</th>
                  <th>更新时间</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach($portfolios as $portfolio): ?>
                  <tr>
                    <td><a href="/portfolio/<?= $portfolio->get('objectId') ?>"><?= $portfolio->get('symbol') ?></a></td>
                    <td><?= $portfolio->get('name') ?></td>
                    <td><?= $portfolio->get('status') == 1? '运行' : '暂停' ?></td>
                    <td><?= $portfolio->get('last_rb_id') ?></td>
                    <td><?= $portfolio->get('period')[0] ?></td>
                    <td><?= $portfolio->get('period')[1] ?></td>
                    <td><?= $portfolio->get('period')[2] ?></td>
                    <td><?= $portfolio->get('updatedAt')->format("Y-m-d H:i:s") ?></td>
                  </tr>

                <?php endforeach ?>
              </tbody>
            </table>
            <h2>调仓记录</h2>
            <table class="table table-striped table-bordered rounded">
              <thead>
                <tr>
                  <th>#标识</th>
                  <th>名称</th>
                  <th>时间</th>
                  <th>类别</th>
                  <th>状态</th>
                  <th>证券名称</th>
                  <th>证券代码</th>
                  <th>前持仓</th>
                  <th>后持仓</th>
                  <th>成交价</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach($portfolios as $portfolio): ?>
                  <?php $balance = $portfolio->rebalancing;?>
                  <?php if(!empty($balance)): ?>
                    <?php $rebalancing_histories = json_decode($balance->get('rebalancing_histories')); $rowNum = count($rebalancing_histories); ?>
                    <tr class="<?= $balance->get('error_code') == 'null'? '':'table-danger' ?><?= $balance->get('prev_bebalancing_id') != 0? '':' table-info' ?>">
                      <td rowspan="<?= $rowNum ?>"><a href="/portfolio/<?= $portfolio->get('objectId') ?>"><?= $portfolio->get('symbol') ?></a></td>
                      <td rowspan="<?= $rowNum ?>"><?= $portfolio->get('name') ?></td>
                      <td rowspan="<?= $rowNum ?>"><?= date("Y-m-d H:i:s", $rebalancing_histories[0]->created_at/1000) ?></td>
                      <td rowspan="<?= $rowNum ?>"><?= $balance->get('category') == 'user_rebalancing'? '用户调仓':'系统调仓' ?></td>
                      <?php if($balance->get('error_code') == 'null'): ?>
                        <td rowspan="<?= $rowNum ?>">成功</td>
                      <?php else:?>
                        <td rowspan="<?= $rowNum ?>" data-toggle="tooltip" data-placement="top" title="<?= $balance->get('error_message') ?>">失败 <span data-feather="help-circle"></span></td>
                      <?php endif ?>
                      <td><?= $rebalancing_histories[0]->stock_name ?></td>
                      <td><?= $rebalancing_histories[0]->stock_symbol ?></td>
                      <td><?= $rebalancing_histories[0]->weight == 0 ? '0.00%': number_format($rebalancing_histories[0]->weight, 2).'%' ?></td>
                      <td><?= $rebalancing_histories[0]->target_weight == 0 ? '0.00%': number_format($rebalancing_histories[0]->target_weight, 2).'%' ?></td>
                      <td>¥<?= $rebalancing_histories[0]->price ?></td>
                      <?php unset($rebalancing_histories[0]) ?>
                    </tr>
                    <?php if($rowNum > 1): ?>
                      <?php foreach ($rebalancing_histories as $value): ?>
                    <tr class="<?= $balance->get('error_code') == 'null'? '':'table-danger' ?><?= $balance->get('prev_bebalancing_id') != 0? '':' table-info' ?>">
                      <td><?= $value->stock_name ?></td>
                      <td><?= $value->stock_symbol ?></td>
                      <td><?= $value->weight == 0 ? '0.00%': number_format($value->weight, 2).'%' ?></td>
                      <td><?= $value->target_weight == 0 ? '0.00%': number_format($value->target_weight, 2).'%' ?></td>
                      <td>¥<?= $value->price ?></td>
                    </tr>
                      <?php endforeach ?>
                    <?php endif ?>
                  <?php else: ?>
                    <tr>
                      <td><a href="/portfolio/<?= $portfolio->get('objectId') ?>"><?= $portfolio->get('symbol') ?></a></td>
                      <td><?= $portfolio->get('name') ?></td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                    <tr>
                  <?php endif ?>
                  <?php endforeach ?>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="//unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>

  </body>
</html>
