<!doctype html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport"
        content="width=device-width, initial-scale=1">
  <title>组合列表</title>

  <!-- Set render engine for 360 browser -->
  <meta name="renderer" content="webkit">

  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/amazeui/2.7.2/css/amazeui.min.css">
  <link rel="stylesheet" href="/stylesheets/mescroll.min.css">
	<script src="/javascript/mescroll.min.js" charset="utf-8"></script>
  <link rel="stylesheet" href="/stylesheets/mobile.css">
</head>
<body>
  <div id="mescroll" class="mescroll">
		<div>
      <div class="am-g am-margin-top">
        <div class="am-u-sm-12">
          <h1><?= $title ?></h1>
          <table class="am-table">
            <thead>
              <tr>
                <th>组合名称</th>
                <th>最近调仓</th>
                <th>调仓证券</th>
              </tr>
            </thead>
            <tbody>
              <?php foreach($portfolios as $portfolio): ?>
                <?php $rebalancing_histories = json_decode($portfolio->lastBalance->get('rebalancing_histories')); $rowNum = count($rebalancing_histories); ?>
                <tr>
                  <td rowspan="<?= $rowNum ?>" class="stock_name"><a href="#"><?= $portfolio->get('name') ?></a></td>

                  <td rowspan="<?= $rowNum ?>"><?= $portfolio->updatedAtDiff ?></td>

                  <td><?= $rebalancing_histories[0]->stock_name ?></td>
                  <?php unset($rebalancing_histories[0]) ?>
                </tr>
                <?php if($rowNum > 1): ?>
                  <?php foreach ($rebalancing_histories as $rebalance): ?>
                    <?php if(!emtpy($rebalance->stock_name)): ?>
                    <tr>
                    <td><?= $rebalance->stock_name ?></td>
                    <tr>
                    <?php endif ?>
                  <?php endforeach?>
                <?php endif ?>

              <?php endforeach ?>
            </tbody>
          </table>
        </div>
      </div>
		</div>
	</div>


<!--[if (gte IE 9)|!(IE)]><!-->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!--<![endif]-->
<!--[if lte IE 8 ]>
<script src="http://libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->
<script src="//cdnjs.cloudflare.com/ajax/libs/amazeui/2.7.2/js/amazeui.min.js"></script>

<script>
$("#mescroll").data("downCount", 0);
var mescroll = new MeScroll("mescroll", {

        down: {
          auto: false,
          htmlContent: '<p class="downwarp-tip">组合刷新中...</p>',
					callback: downCallback
				}
			});
function downCallback() {
  location.reload();
  //
}
</script>
</body>
</html>
