<!doctype html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport"
        content="width=device-width, initial-scale=1">
  <title>Amaze UI Examples</title>

  <!-- Set render engine for 360 browser -->
  <meta name="renderer" content="webkit">

  <link rel="stylesheet" href="//cdn.amazeui.org/amazeui/2.7.2/css/amazeui.min.css">
  <link rel="stylesheet" href="/stylesheets/mobile.css">
</head>
<body>
  <div class="am-g">
    <div class="am-u-sm-12">
      <h1><?= $title ?></h1>
      <table class="am-table">
        <thead>
          <tr>
            <th>名称</th>
            <th>更新时间</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach($portfolios as $portfolio): ?>
            <tr>
              <td><a href="/portfolio/<?= $portfolio->get('objectId') ?>"><?= $portfolio->get('name') ?></a></td>

              <td><?= $portfolio->get('updatedAt')->format("Y-m-d H:i:s") ?></td>
            </tr>
          <?php endforeach ?>
        </tbody>
      </table>
    </div>
  </div>


<!--[if (gte IE 9)|!(IE)]><!-->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!--<![endif]-->
<!--[if lte IE 8 ]>
<script src="http://libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->
<script src="//cdn.amazeui.org/amazeui/2.7.2/js/amazeui.min.js"></script>
</body>
</html>
