<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Stock Monitor</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/stylesheets/dashboard.css" rel="stylesheet">
  </head>

  <body>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <a class="navbar-brand col-sm-12 col-md-12 mr-0" href="#">雪球投资组合监控小帮手</a>
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="/">
                  <span data-feather="home"></span>
                  控制台 <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/portfolios">
                  <span data-feather="file"></span>
                  组合列表
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/contacts">
                  <span data-feather="shopping-cart"></span>
                  监控提醒
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logs">
                  <span data-feather="bar-chart-2"></span>
                  运行日志
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/setting">
                  <span data-feather="layers"></span>
                  系统设置
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>待办事项</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2"><?= $portfolio->get('name') ?> <a href="https://xueqiu.com/P/<?= $portfolio->get('symbol') ?>" target="_blank"><small><?= $portfolio->get('symbol') ?> </small> <span data-feather="external-link"></span></a></h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">导出</button>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <h2>调仓记录</h2>
              <table class="table table-striped table-bordered rounded">
                <thead>
                  <tr>
                    <th>#ID</th>
                    <th>类别</th>
                    <th>状态</th>
                    <th>证券名称</th>
                    <th>证券代码</th>
                    <th>前持仓</th>
                    <th>后持仓</th>
                    <th>成交价</th>
                    <th>调仓时间</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach($allBalance as $balance): ?>
                    <?php $rebalancing_histories = json_decode($balance->get('rebalancing_histories')); $rowNum = count($rebalancing_histories); ?>
                    <tr>
                      <td rowspan="<?= $rowNum ?>"><?= $balance->get('origin_id') ?></td>
                      <td rowspan="<?= $rowNum ?>"><?= $balance->get('category') == 'user_rebalancing'? '用户调仓':'系统调仓' ?></td>
                      <td rowspan="<?= $rowNum ?>"><?= $balance->get('status') == 'success'? '成功':'失败' ?></td>
                      <td><?= $rebalancing_histories[0]->stock_name ?></td>
                      <td><?= $rebalancing_histories[0]->stock_symbol ?></td>
                      <td><?= $rebalancing_histories[0]->prev_weight == 0 ? '0.00%': number_format($rebalancing_histories[0]->prev_weight, 2).'%' ?></td>
                      <td><?= $rebalancing_histories[0]->target_weight == 0 ? '0.00%': number_format($rebalancing_histories[0]->target_weight, 2).'%' ?></td>
                      <td>¥<?= $rebalancing_histories[0]->price ?></td>
                      <td><?= date("Y-m-d H:i:s", $rebalancing_histories[0]->created_at/1000) ?></td>
                      <?php unset($rebalancing_histories[0]) ?>
                    </tr>
                    <?php if($rowNum > 1): ?>
                      <?php foreach ($rebalancing_histories as $value): ?>
                    <tr>
                      <td><?= $value->stock_name ?></td>
                      <td><?= $value->stock_symbol ?></td>
                      <td><?= $value->prev_weight == 0 ? '0.00%': number_format($value->prev_weight, 2).'%' ?></td>
                      <td><?= $value->target_weight == 0 ? '0.00%': number_format($value->target_weight, 2).'%' ?></td>
                      <td>¥<?= $value->price ?></td>
                      <td><?= date("Y-m-d H:i:s", $value->created_at/1000) ?></td>
                    </tr>
                      <?php endforeach ?>
                    <?php endif ?>
                  <?php endforeach ?>
                </tbody>
              </table>
            </div>
          </div>


        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="//unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <script src="//cdn.jsdelivr.net/npm/leancloud-storage@3.10.0/dist/av-live-query-min.js"></script>
    <script>
      // 存储服务
      var { Query, User } = AV;
      AV.init('PAULNEyX9yOQ2Nl1yvOIugpf-gzGzoHsz', 'U6ofyNOgAAzuOiOzFaibGwsx');
      // 实时消息服务
      var { Realtime, TextMessage } = AV;
      //localStorage.setItem('debug', 'LC*');
      var doingQuery = new AV.Query('Portfolios').equalTo('symbol', '<?= $portfolio->get('symbol') ?>');

      doingQuery.find().then(function(doingList) {
        console.log(doingList);
      });

      doingQuery.subscribe().then(function(liveQuery) {
          // liveQuery 是 doingQuery 的订阅
          liveQuery.on('update', function(newDoingItem) {
            // add newDoingItem to doingList
            console.log(newDoingItem)
          });
      });
    </script>
  </body>
</html>
