<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Stock Monitor</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/stylesheets/dashboard.css" rel="stylesheet">
  </head>

  <body>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <a class="navbar-brand col-sm-12 col-md-12 mr-0" href="#">雪球投资组合监控小帮手</a>
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="/">
                  <span data-feather="home"></span>
                  控制台 <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/portfolios">
                  <span data-feather="file"></span>
                  组合列表
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  监控提醒
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  运行日志
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                  系统设置
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">组合列表</h1>
          </div>

          <div class="row">
            <div class="col-4">
              <div class="card">
                <div class="card-header">
                  新增组合
                </div>
                <div class="card-body">
                  <form action="/portfolios" method="POST">
                    <div class="form-group">
                      <label for="exampleInputEmail1">雪球组合唯一标识符</label>
                      <input type="text" name="symbol" class="form-control" id="inputSymbol" aria-describedby="symbolHelp" placeholder="ZH1230914">
                      <small id="symbolHelp" class="form-text text-muted">https://xueqiu.com/p/<span class="text-danger">ZH1230914</span> <b>链接红色部份</b></small>
                    </div>
                    <button type="submit" class="btn btn-primary">提交</button>
                  </form>
                </div>
              </div>


            </div>
            <div class="col">
              <table class="table table-striped table-bordered rounded">
                <thead>
                  <tr>
                    <th>#标识</th>
                    <th>名称</th>
                    <th>状态</th>
                    <th>日涨跌</th>
                    <th>月涨跌</th>
                    <th>净值</th>
                    <th>更新时间</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach($portfolios as $portfolio): ?>
                    <tr>
                      <td><a href="/portfolio/<?= $portfolio->get('objectId') ?>"><?= $portfolio->get('symbol') ?></a></td>
                      <td><?= $portfolio->get('name') ?></td>
                      <td><?= $portfolio->get('status') == 1? '运行' : '暂停' ?></td>
                      <td><?= $portfolio->get('period')[0] ?></td>
                      <td><?= $portfolio->get('period')[1] ?></td>
                      <td><?= $portfolio->get('period')[2] ?></td>
                      <td><?= $portfolio->get('updatedAt')->format("Y-m-d H:i:s") ?></td>
                    </tr>
                  <?php endforeach ?>
                </tbody>
              </table>
            </div>
          </div>


        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="//unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
  </body>
</html>
