<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Stock Monitor</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/stylesheets/dashboard.css" rel="stylesheet">
  </head>

  <body>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <a class="navbar-brand col-sm-12 col-md-12 mr-0" href="#">雪球投资组合监控小帮手</a>
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="/">
                  <span data-feather="home"></span>
                  控制台 <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/portfolios">
                  <span data-feather="file"></span>
                  组合列表
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/contacts">
                  <span data-feather="shopping-cart"></span>
                  监控提醒
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logs">
                  <span data-feather="bar-chart-2"></span>
                  运行日志
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/setting">
                  <span data-feather="layers"></span>
                  系统设置
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>待办事项</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">组合列表</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>

          <div class="row">
            <div class="col-4">
              <div class="card">
                <div class="card-header">
                  新增组合
                </div>
                <div class="card-body">
                  <form action="/portfolios" method="POST">
                    <div class="form-group">
                      <label for="exampleInputEmail1">雪球组合唯一标识符</label>
                      <input type="text" name="symbol" class="form-control" id="inputSymbol" aria-describedby="symbolHelp" placeholder="ZH1230914">
                      <small id="symbolHelp" class="form-text text-muted">https://xueqiu.com/p/<span class="text-danger">ZH1230914</span> <b>链接红色部份</b></small>
                    </div>
                    <button type="submit" class="btn btn-primary">提交</button>
                  </form>
                </div>
              </div>


            </div>
            <div class="col">
              <table class="table table-striped table-bordered rounded">
                <thead>
                  <tr>
                    <th>#标识</th>
                    <th>名称</th>
                    <th>净值</th>
                    <th>日收益</th>
                    <th>月收益</th>
                    <th>总收益</th>
                    <th>更新时间</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach($portfolios as $portfolio): ?>
                    <tr>
                      <td><a href="https://xueqiu.com/p/<?= $portfolio->get('symbol') ?>"><?= $portfolio->get('symbol') ?></a></td>
                      <td>Lorem</td>
                      <td>ipsum</td>
                      <td>dolor</td>
                      <td>dolor</td>
                      <td>dolor</td>
                      <td><?= $portfolio->get('updated') ?></td>
                    </tr>
                  <?php endforeach ?>
                </tbody>
              </table>
            </div>
          </div>


        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
  </body>
</html>
