<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Stock Monitor</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/stylesheets/dashboard.css" rel="stylesheet">
  </head>

  <body>

    <div class="container-fluid">
      <div class="row">


        <div class="col pt-3 pb-3">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2"><a href="/">控制台</a>>><a href="/portfolios">组合列表</a>>><a href="#" target="_blank"><?= $portfolio->get('name') ?><?= $portfolio->get('symbol') ?> <span data-feather="external-link"></span></a></h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">导出</button>
              </div>
            </div>
          </div>
          <div class="alert alert-danger alert-dismissible fade show" style="display:none;" role="alert" id="rebalancing_warning">
            <strong>请注意！</strong> 该组合有新的调仓.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="row">
            <div class="col">
              <h2>近期调仓</h2>
              <table class="table table-striped table-bordered rounded">
                <thead>
                  <tr>
                    <th>时间</th>
                    <th>类别</th>
                    <th>状态</th>
                    <th>证券名称</th>
                    <th>证券代码</th>
                    <th>前持仓</th>
                    <th>后持仓</th>
                    <th>成交价</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach($allBalance as $balance): ?>
                    <?php $rebalancing_histories = json_decode($balance->get('rebalancing_histories')); $rowNum = count($rebalancing_histories); ?>
                    <tr class="<?= $balance->get('error_code') == 'null'? '':'table-danger' ?><?= $balance->get('prev_bebalancing_id') != 0? '':' table-info' ?>">
                      <td rowspan="<?= $rowNum ?>"><?= date("Y-m-d H:i:s", $rebalancing_histories[0]->updated_at/1000) ?></td>
                      <td rowspan="<?= $rowNum ?>"><?= $balance->get('category') == 'user_rebalancing'? '用户调仓':'系统调仓' ?></td>
                      <?php if($balance->get('error_code') == 'null'): ?>
                        <td rowspan="<?= $rowNum ?>">成功</td>
                      <?php else:?>
                        <td rowspan="<?= $rowNum ?>" data-toggle="tooltip" data-placement="top" title="<?= $balance->get('error_message') ?>">失败 <span data-feather="help-circle"></span></td>
                      <?php endif ?>
                      <td><?= $rebalancing_histories[0]->stock_name ?></td>
                      <td><?= $rebalancing_histories[0]->stock_symbol ?></td>
                      <td><?= $rebalancing_histories[0]->prev_weight == 0 ? '0.00%': number_format($rebalancing_histories[0]->prev_weight, 2).'%' ?></td>
                      <td><?= $rebalancing_histories[0]->target_weight == 0 ? '0.00%': number_format($rebalancing_histories[0]->target_weight, 2).'%' ?></td>
                      <td>¥<?= $rebalancing_histories[0]->price ?></td>
                      <?php unset($rebalancing_histories[0]) ?>
                    </tr>
                    <?php if($rowNum > 1): ?>
                      <?php foreach ($rebalancing_histories as $value): ?>
                    <tr class="<?= $balance->get('error_code') == 'null'? '':'table-danger' ?><?= $balance->get('prev_bebalancing_id') != 0? '':' table-info' ?>">
                      <td><?= $value->stock_name ?></td>
                      <td><?= $value->stock_symbol ?></td>
                      <td><?= $value->prev_weight == 0 ? '0.00%': number_format($value->prev_weight, 2).'%' ?></td>
                      <td><?= $value->target_weight == 0 ? '0.00%': number_format($value->target_weight, 2).'%' ?></td>
                      <td>¥<?= $value->price ?></td>
                    </tr>
                      <?php endforeach ?>
                    <?php endif ?>
                  <?php endforeach ?>
                </tbody>
              </table>
            </div>
          </div>


        </div>
      </div>
    </div>
    <audio src="//wx.flunar.com/audio/dog.mp3" preload="meta" loop id="warning_tone"></audio>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="//unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>

    <script src="//cdn.jsdelivr.net/npm/leancloud-storage@3.10.0/dist/av-live-query-min.js"></script>
    <script>
      // 存储服务
      var { Query, User } = AV;
      AV.init('<?= getenv("LEANCLOUD_APP_ID") ?>', '<?= getenv("LEANCLOUD_APP_KEY") ?>');
      // 实时消息服务
      var { Realtime, TextMessage } = AV;
      //localStorage.setItem('debug', 'LC*');
      var doingQuery = new AV.Query('Portfolios').equalTo('symbol', '<?= $portfolio->get('symbol') ?>');

      var warning_tone = document.getElementById('warning_tone');
      doingQuery.find().then(function(doingList) {
        //console.log(doingList);

      });

      //console.log(doingQuery)
      doingQuery.subscribe().then(function(liveQuery) {

          // liveQuery 是 doingQuery 的订阅
          liveQuery.on('update', function(newDoingItem) {
            // add newDoingItem to doingList
            $('#rebalancing_warning').show();
            console.log(newDoingItem)
            if(warning_tone.paused){
              warning_tone.play();
            }
          });
      });
      $('button.close').click(function () {
          warning_tone.pause();
          $('#rebalancing_warning').hide();
          location.reload();
      });
    </script>
  </body>
</html>
